name: Node CI

on:
  - push
  - pull_request

jobs:
  build:

    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Using eslint
        run: make lint
